### PR TITLE
fix: Component notes do not work when using twigAdapter

### LINKED ISSUE #45: Component notes not working when using twigAdapter as docs engine
Setting the `fractal.docs.engine(twigAdapter);` work as expected for markdown files located in the folder defined by `fractal.docs.set('path', ...);`, but it seem to break the note panel / note templating engine for a component with a readme.md (https://fractal.build/guide/components/notes.html#the-readme-md-file)

It still break even if I simply use plain text, nothing related to twig. 
The error only occurs on component with a readme.md file.

And this is the error in question : 
```
 (C:\projects\_internal\frontend-structure\_frontend\node_modules\@frctl\mandelbrot\views\pages\components\detail.nunj)
  Template render error: (C:\projects\_internal\frontend-structure\_frontend\node_modules\@frctl\mandelbrot\views\partials\pen\browser.nunj)
  Template render error: (C:\projects\_internal\frontend-structure\_frontend\node_modules\@frctl\mandelbrot\views\partials\browser\browser.nunj)
  Template render error: (C:\projects\_internal\frontend-structure\_frontend\node_modules\@frctl\mandelbrot\views\partials\browser\panel-notes.nunj)
  TypeError: The "to" argument must be of type string. Received type object
```

image

### PR DESCRIPTION
**Pull request by rchavik**
Closes: #45

### CODE REVIEW

File: src/adapter.js [hunk 1]
```diff
@@ -143,6 +143,10 @@ class TwigAdapter extends Fractal.Adapter {
 
         return new Promise(function(resolve, reject){
 
+            if (path == null) {
+                return resolve(str);
```
Comment (mihkeleidast) [inline src/adapter.js]: returning early means that the notes are not passed through the twig engine at all, which is also unexpected.

i would remove that if and on the following line, conditionally use `Path.relative`:
```js
let tplPath = path ? Path.relative(self._source.fullPath, path) : undefined;
```

That would, in my testing, make the most of the situation. For example, that will allow users to use the global data that is passed into context in the notes file:
```
## config
<ul>
{% for key, value in _config %}
  <li>{{ key }}: {{ value }}</li>
{% endfor %}
</ul>
```

**Review by mihkeleidast — CHANGES_REQUESTED** [review]

File: src/adapter.js (hunk 1 above)
Comment (rchavik) [reply src/adapter.js]: You're right. I have updated the PR.

**Review by mihkeleidast — APPROVED** [review]
